### ISSUE TITLE
Null pointer at Piece.java on piece generation

### ISSUE THREAD

**Issue by Sneakercopter** [SQA-Tetris/Tetris#5]
- Null pointer on variable (not resolved) in commit [0fbb3fea8d7044a45277f7b20e584272e19f14d4](https://github.com/SQA-Tetris/Tetris/commit/0fbb3fea8d7044a45277f7b20e584272e19f14d4)

**Comment by Mirka-exe** [comment]
Error occured in: [0fbb3fea8d](https://github.com/SQA-Tetris/Tetris/tree/0fbb3fea8d7044a45277f7b20e584272e19f14d4)

Error occured due: variable shapeCoordinates not initialized

Error supposedly fixed in: [905f42e3a1](https://github.com/SQA-Tetris/Tetris/tree/905f42e3a1bff6c33e4519d225f4781b498861d2)

@mikeynic Please test if the problem has been resolved

**Comment by mikeynic** [comment]
Hi Mirka, 
Thanks for the updated code, I have run my test and the game does not crash anymore. I would suggest sticking to our code guidelines next time!
